services:
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/:/app/
    network_mode: host
  backend:
    build: ./backend/
    volumes:
      - ./backend/:/server/
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
